### ISSUE TITLE
中文交流贴

### ISSUE THREAD

**Issue by LamzZ2** [CaptainEven/Vehicle-Car-detection-and-multilabel-classification#4]
请问作者是怎么制作数据集的呢，主要想知道如何准备数据集的标签，我们现在也在做车辆检测和多属性识别

**Comment by LamzZ2** [comment]
还有个问题，如何做到实时检测和多属性识别的呀，这个多属性识别如何接进去的呢

**Comment by CaptainEven** [comment]
第一个问题：
(1) . 检测部分的训练数据标签跟YOLO(darknet)保持一致cls_id x, y, w, h(对img_w, img_h的相对值)；
(2). 识别部分的标签： 将组合特征一致的数据放到根目录下对应的子目录，子目录名成即label值，具体处理见代码：训练、测试数据类别按照子目录存放，子目录名即label，Color_Direction_type，如Yellow_Rear_suv
第二个问题:
在检测的基础上做识别，依据检测额bbox切ROI，仅仅使用ROI做识别。

**Comment by LamzZ2** [comment]
> 第一个问题：
> （1）。检测部分的训练数据标签跟YOLO（darknet）保持一致cls_id x，y，w，h（对img_w，img_h的相对值）; 
> （2）。识别部分的标签：将组合特征一致的数据放到根目录下对应的子目录，子目录名成即标签值，具体处理见代码：训练，测试数据类别按照子目录存放，子目录名即标签， Color_Direction_type，如Yellow_Rear_suv 
> 第二个问题：
> 在检测的基础上做识别，依据检测额BBOX切的投资回报率，仅仅使用ROI做识别。

谢谢指导  后续进展还有疑问请多多指教

**Comment by LamzZ2** [comment]
> 第一个问题：
> （1）。检测部分的训练数据标签跟YOLO（darknet）保持一致cls_id x，y，w，h（对img_w，img_h的相对值）; 
> （2）。识别部分的标签：将组合特征一致的数据放到根目录下对应的子目录，子目录名成即标签值，具体处理见代码：训练，测试数据类别按照子目录存放，子目录名即标签， Color_Direction_type，如Yellow_Rear_suv 
> 第二个问题：
> 在检测的基础上做识别，依据检测额BBOX切的投资回报率，仅仅使用ROI做识别。

刚刚看到老哥是武汉人，有缘啊，我是鄂州人，老乡，打个招呼
顺便再请教一个问题
就是多属性识别的数据集，我想自己准备，有必要把每一张的ROI截取下来进行训练吗？还是说留一点背景也可以呢  我想用MIT Cars dataset作为训练集试试

**Comment by CaptainEven** [comment]
是的，一张一张的截取ROI，ROI跟bounding box一样就可以，写过一个半自动化的GUI工具，可以加快这个过程，这两天会放上来。

**Comment by nobody-cheng** [comment]
> 请问作者是怎么制作数据集的呢，主要想知道如何准备数据集的标签，我们现在也在做车辆检测和多属性识别
同问如何制作数据集，非常谢谢

**Comment by ArchieGu** [comment]
> > 请问作者是怎么制作数据集的呢，主要想知道如何准备数据集的标签，我们现在也在做车辆检测和多属性识别
> > 同问如何制作数据集，非常谢谢
同问，我现在如果是要做监控摄像头这个角度的数据集，估计数据收集和打标签的过程就得清楚才行了。

**Comment by CaptainEven** [comment]
@ArchieGu 参考Clipper.py

**Comment by gongjing1996** [comment]
请问一下cfg文件里的share=0是什么呀？我直接在darknet版下面用cfg和weights在bdd100k上测试了一下，结果不太好。想请问一下基于你的数据集的测试结果？

**Comment by littlePrince126** [comment]
想请教一下，在车辆检测中，你用到的是哪些数据集来训练，让yolov3-tiny有这么好的检测效果？感谢

**Comment by CoffinIan** [comment]
您好 我最近也在做车辆识别 在用您的模型跑我自己的数据的时候一直出现这个错误 您知道是什么回事吗

Traceback (most recent call last):
  File "C:/Users/Ian/Desktop/front_or_back/run.py", line 221, in <module>
    DR_model.detect_classify()
  File "C:/Users/Ian/Desktop/front_or_back/run.py", line 209, in detect_classify
    self.cls_draw_bbox(output, orig_img)
  File "C:/Users/Ian/Desktop/front_or_back/run.py", line 153, in cls_draw_bbox
    ROI = Image.fromarray(orig_img[pt_1[1]: pt_2[1], pt_1[0]: pt_2[0]][:, :, ::-1])
  File "E:\conda\envs\pytorch-cpu\lib\site-packages\PIL\Image.py", line 2670, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "E:\conda\envs\pytorch-cpu\lib\site-packages\PIL\Image.py", line 2613, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "E:\conda\envs\pytorch-cpu\lib\site-packages\PIL\Image.py", line 2546, in frombytes
    im.frombytes(data, decoder_name, args)
  File "E:\conda\envs\pytorch-cpu\lib\site-packages\PIL\Image.py", line 829, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image

**Comment by zhangkaijing960806** [comment]
请教下作者，我测试自己的数据，提示外部图像无法扩展，这个是什么原因呢

**Comment by LegendSun0** [comment]
> 请教下作者，我测试自己的数据，提示外部图像无法扩展，这个是什么原因呢

麻烦问下这个问题解决了么？

**Comment by Apuruuu** [comment]
> > 请教下作者，我测试自己的数据，提示外部图像无法扩展，这个是什么原因呢
> 
> 麻烦问下这个问题解决了么？

我发现如果被检测图片中没有能被识别到的车辆就会报错，提示：tile cannot extend outside image，应该就是你们说的“外部图像无法扩展”。看了别人的回复，有人推测是因为黄色框顶部的标签无法被写在图像外部。实际查看pt_1，pt_2两个变量在未检测出车辆时，元组1 张量的第一个元素是0（猜测代表y轴位置=0）。所以在262行加入了如果左上角坐标pt_1的y轴=0的话跳出的机制。并且在紧接着的一个for循环中也加入了跳出机制，使得程序不会报错，并让这张未检测出车辆的图像能出现在test_result/ 目录中。

我在VehicleDC.py的第262行之后加上：

            pt_2 = tuple(det[3:5].int())  # the right down point  #原文件的262行  

            ## 没检测到的话 break
            if pt_1[1].item() == 0:
                break

并且在第280行之后加入：

        for i, det in enumerate(output):  #原文件的280行  

            ## 没检测到的话 break
            if pt_1s == []:
                break

我因为毕设才接触的车辆识别检测，并且python也刚学习不久。这个改动虽然解决了“tile cannot extend outside image”的问题，但做法并不好，也没有测试如果在画面最上方检测出车辆时是否也会被跳出。如果有其他方法还请多指教。

**Comment by zzcqinag** [comment]
老乡好!我也是武汉的,请问下训练的时候,local paths和remote paths这两个有什么作用?谢谢 @CaptainEven
